# Generated by Django 6.0.1 on 2026-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField()),
                ('No_of_people', models.IntegerField()),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
