# Generated by Django 6.0.1 on 2026-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='Email',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
